### ISSUE TITLE
psconfig remote add (from_local_file) fails

### ISSUE THREAD

**Issue by igarny** [perfsonar/psconfig#24] opened 2018-07-17 10:14 UTC
After adding and removal of a mesh config, pScfg breaks the syntax or anyway leads to errors. 
After this I am not able to add other meshes / urls in the configuraiton using the `psconfig remote` command
Tested on CentOS 7
```
[~]$ cat /etc/perfsonar/psconfig/maddash-agent.json | jq .
{
  "remotes": [
    {}
  ],
  "grids": {
    "default_ping_loss": {
      "priority": {
        "level": 1,
        "group": "ping_loss"
      },
      "check": {
        "type": "ps-nagios-ping-loss"
      },
      "visualization": {
        "type": "ps-graphs"
      },
      "display-name": "Ping Loss"
    },
    "default_trace": {
      "priority": {
        "level": 1,
        "group": "trace"
      },
      "check": {
        "type": "ps-nagios-traceroute"
      },
      "visualization": {
        "type": "ps-traceroute-viewer"
      },
      "display-name": "Path Count"
    },
    "default_throughput": {
      "priority": {
        "level": 1,
        "group": "throughput"
      },
      "check": {
        "type": "ps-nagios-throughput"
      },
      "visualization": {
        "type": "ps-graphs"
      },
      "display-name": "Throughput"
    },
    "default_loss": {
      "priority": {
        "level": 1,
        "group": "loss"
      },
      "check": {
        "type": "ps-nagios-loss"
      },
      "visualization": {
        "type": "ps-graphs"
      },
      "display-name": "Loss"
    }
  }
}
[~]$ psconfig remote list
=== MaDDash Agent ===
/etc/perfsonar/psconfig/maddash-agent.json is not valid. The following errors were encountered:
    JSON Path: /remotes/0/url
    Error: Missing property.

[~]$ sudo psconfig remote add http://perfsonar-stage-ma.grnoc.iu.edu/mesh_config/staging-testbed.json
=== MaDDash Agent ===
/etc/perfsonar/psconfig/maddash-agent.json is not valid. The following errors were encountered:
    JSON Path: /remotes/0/url
    Error: Missing property.

[~]$
[~]$
[~]$ psconfig remote list
=== MaDDash Agent ===
/etc/perfsonar/psconfig/maddash-agent.json is not valid. The following errors were encountered:
    JSON Path: /remotes/0/url
    Error: Missing property.

```

**Comment by arlake228** [comment] 2018-07-17 10:21
I assume you edited by hand? The syntax of the file is incorrect. You need
to remove the empty curly braces in "remotes". Syntax errors like this is
the risk of editing by hand.

**Comment by igarny** [comment] 2018-07-17 10:29
Actually not.
This happened for me, when adding a broken mesh config from a local file using `psconfig remote add`
After I try to remove the broken config with `psconfig remote delete`, it leaves the broken syntax after itself.

 On top of that it is again strange, since this is my current GEANT production mesh, which is found broken (still this is not the subject here).

**Comment by igarny** [comment] 2018-07-17 10:30
I have reproduced the issue again.

**Comment by arlake228** [comment] 2018-07-17 10:33
Can you share the exact sequence of commands you use to reproduce?

**Comment by igarny** [comment] 2018-07-17 10:36
```
[~]$ psconfig remote list
=== MaDDash Agent ===
[
   {
      "url" : "http://perfsonar-stage-ma.grnoc.iu.edu/mesh_config/staging-testbed.json"
   }
]
[~]$
[~]$
[~]$
[~]$
[~]$ sudo psconfig remote delete http://perfsonar-stage-ma.grnoc.iu.edu/mesh_config/staging-testbed.json
=== MaDDash Agent ===
Removed remote configuration for http://perfsonar-stage-ma.grnoc.iu.edu/mesh_config/staging-testbed.json
[~]$ psconfig remote list
=== MaDDash Agent ===
[]
[~]$
[~]$
[~]$
[~]$ sudo psconfig remote add /var/www/html/mesh/gnintmesh.json
=== MaDDash Agent ===
Added remote configuration /var/www/html/mesh/gnintmesh.json
[~]$ psconfig remote list
=== MaDDash Agent ===
/etc/perfsonar/psconfig/maddash-agent.json is not valid. The following errors were encountered:
    JSON Path: /remotes/0/url
    Error: Missing property.

[~]$ sudo psconfig remote delete /var/www/html/mesh/gnintmesh.json
=== MaDDash Agent ===
/etc/perfsonar/psconfig/maddash-agent.json is not valid. The following errors were encountered:
    JSON Path: /remotes/0/url
    Error: Missing property.

[~]$ psconfig remote list
=== MaDDash Agent ===
/etc/perfsonar/psconfig/maddash-agent.json is not valid. The following errors were encountered:
    JSON Path: /remotes/0/url
    Error: Missing property.

[~]$ cat /etc/perfsonar/psconfig/maddash-agent.json | jq .
{
  "remotes": [
    {}
  ],
  "grids": {
    "default_ping_loss": {
      "priority": {
        "level": 1,
        "group": "ping_loss"
      },
      "check": {
        "type": "ps-nagios-ping-loss"
      },
      "visualization": {
        "type": "ps-graphs"
      },
      "display-name": "Ping Loss"
    },
    "default_trace": {
      "priority": {
        "level": 1,
        "group": "trace"
      },
      "check": {
        "type": "ps-nagios-traceroute"
      },
      "visualization": {
        "type": "ps-traceroute-viewer"
      },
      "display-name": "Path Count"
    },
    "default_throughput": {
      "priority": {
        "level": 1,
        "group": "throughput"
      },
      "check": {
        "type": "ps-nagios-throughput"
      },
      "visualization": {
        "type": "ps-graphs"
      },
      "display-name": "Throughput"
    },
    "default_loss": {
      "priority": {
        "level": 1,
        "group": "loss"
      },
      "check": {
        "type": "ps-nagios-loss"
      },
      "visualization": {
        "type": "ps-graphs"
      },
      "display-name": "Loss"
    }
  }
}
[~]$
```

**Comment by igarny** [comment] 2018-07-17 10:39
Oh I see why it fails for my GEANT mesh....and probably the reason for this issue

I guess I should be using some param to tell pScfg it is a local file

**Comment by igarny** [comment] 2018-07-17 10:46
```
[~]$wget http://perfsonar-stage-ma.grnoc.iu.edu/mesh_config/staging-testbed.json
--2018-07-17 10:42:09--  http://perfsonar-stage-ma.grnoc.iu.edu/mesh_config/staging-testbed.json
Resolving perfsonar-stage-ma.grnoc.iu.edu (perfsonar-stage-ma.grnoc.iu.edu)... 140.182.49.168
Connecting to perfsonar-stage-ma.grnoc.iu.edu (perfsonar-stage-ma.grnoc.iu.edu)|140.182.49.168|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8953 (8.7K) [application/json]
Saving to: вЂstaging-testbed.jsonвЂ™

100%[==================================================================================================================================================>] 8,953       --.-K/s   in 0s

2018-07-17 10:42:09 (202 MB/s) - вЂstaging-testbed.jsonвЂ™ saved [8953/8953]

[~]$ pwd
/home/local/***
[~]$ sudo vi /etc/perfsonar/psconfig/maddash-agent.json
[~]$ sudo psconfig remote add /home/local/***/staging-testbed.json
=== MaDDash Agent ===
Added remote configuration /home/local/***/staging-testbed.json
[~]$ psconfig remote list
=== MaDDash Agent ===
/etc/perfsonar/psconfig/maddash-agent.json is not valid. The following errors were encountered:
    JSON Path: /remotes/0/url
    Error: Missing property.

```

**Comment by arlake228** [comment] 2018-07-17 10:49
There should not be any special option needed for a local file vs a url.
Thanks for the commands. I did a quick look at the source of the remote
command and didn't see anything obvious. I will run through the commands
and see what I can find when i am back at my desk later this morning.

**Comment by igarny** [comment] 2018-07-17 10:51
Oh I can give another hint.
Once the addition of the local file fails, actually it is psconfig that leaves empty braces in the config

**Comment by arlake228** [comment] 2018-07-17 13:52
This should be fixed now. I will build new RPMs so you can get the change.

The problem was two-fold: First, it didn't like that the file path didn't look like a URL with a prefix of http://, etc. It should be allowing file paths, so that should not have been an issue. The second problem was that instead of printing an error, it just didn't fill-in the field and created an empty object. Such validation errors will now be caught and printed to the screen.

Will close once you have a chance to confirm on your side it works.

**Comment by igarny** [comment] 2018-07-19 10:46
Hello Andy
I have tried out the nightly build and specifically the psconfig changes.
I did not come across any issues, apart for some outdated info. Outdated info = references to regulartesting service and bwctl daemon management. 
I believe this is very minor, since these are coming from the example maddash.yaml only

Safe to close

**Comment by arlake228** [comment] 2018-07-19 13:46
Thank you! I will try to get change into staging soon. Hopefully today if I am able to finish a couple other tasks

**Closed by arlake228** 2018-07-19 13:46 UTC
Labels: awaiting-feedback, bug
